name: CI

on:
  push:
    branches: [ main, master, 'feature/*', 'fix/*', 'docs/*', 'test/*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Setup venv
        run: |
          uv venv
          source .venv/bin/activate
          
      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]"
          
      - name: Run linting
        run: |
          ruff format . --check
          ruff check .
          
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml