name: CI

on:
  push:
    branches: [ main, master, 'feature/*', 'fix/*', 'docs/*', 'test/*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Get uv cache dir
        id: get-uv-cache
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_OUTPUT
        
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-uv-cache.outputs.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: Setup venv and tools
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install ruff pytest pytest-cov
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          
      - name: Install package
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          
      - name: Run linting
        run: |
          source .venv/bin/activate
          which ruff
          ruff --version
          ruff format . --check
          ruff check .
          
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=src --cov-report=xml
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml